version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
sphinx:
   configuration: iolite_docs/conf.py

formats:
  - pdf
  - epub

python:
  install:
    - requirements: iolite_docs/requirements.txt